apiVersion: 3
dataDisplay:
  browseContentPretty: false
  browseNavLevel: 2
  exampleSection: piece 1
  exampleSectionHtml: <code>piece 1</code>
  excludedFeatures: []
  noneValues:
  - null
  sectionSep1: ' '
  sectionSep2: ':'
  showVerseInTuple: false
  textFormats: {}
docs:
  charText: How TF features represent text
  charUrl: '{tfDoc}/writing/transcription/'
  docBase: '{docRoot}/{org}/{repo}/blob/master/docs'
  docExt: .md
  docPage: home
  docRoot: '{urlGh}'
  featureBase: null
  featurePage: home
interfaceDefaults:
  lineNumbers: null
  prettyTypes: true
  queryFeatures: true
  showHidden: false
  standardFeatures: true
  showGraphics: null
  withNodes: false
  withTypes: false
provenanceSpec:
  corpus: TF dataset (unspecified)
  doi: null
  graphicsRelative: null
  moduleSpecs: []
  org: annotation
  relative: tf
  repo: default
  version: None
  webBase: null
  webHint: null
  webLang: null
  webLexId: null
  webUrl: null
  webUrlLex: null
  zip: null
typeDisplay:
  piece:
    base: false
    boundary: false
    condense: true
    features: feat3 feat4
    featuresBare: feat1 feat2
    flow: hor
    graphics: null
    level: 1
    lexOcc: slot
    lineNumber: null
    stretch: true
    hidden: false
    label: '{title}'
    template: '{title}'
    style: None
    transform: {}
    verselike: false
    wrap: true
  sign:
    features: feat3
    featuresBare: feat1
writing: ''
